
export type UsersActionType = 
'GETTING_USER_PROFILE' |
'GETTING_USER_PROFILE_SUCCESS' |
'GETTING_USER_PROFILE_FAILURE';

const GETTING_USER_PROFILE: UsersActionType = 'GETTING_USER_PROFILE';
const GETTING_USER_PROFILE_SUCCESS: UsersActionType = 'GETTING_USER_PROFILE_SUCCESS';
const GETTING_USER_PROFILE_FAILURE: UsersActionType = 'GETTING_USER_PROFILE_FAILURE';

export {
  GETTING_USER_PROFILE,
  GETTING_USER_PROFILE_SUCCESS,
  GETTING_USER_PROFILE_FAILURE,
}