
export type ForumActionType = 
  'SUBMITTING_POST' |
  'SUBMITTING_POST_SUCCESS' |
  'SUBMITTING_POST_FAILURE';

const SUBMITTING_POST: ForumActionType = 'SUBMITTING_POST';
const SUBMITTING_POST_SUCCESS: ForumActionType = 'SUBMITTING_POST_SUCCESS';
const SUBMITTING_POST_FAILURE: ForumActionType = 'SUBMITTING_POST_FAILURE';

export {
  SUBMITTING_POST,
  SUBMITTING_POST_SUCCESS,
  SUBMITTING_POST_FAILURE
}